### ISSUE TITLE
关于gitlab graphQL Api的一些请教

### ISSUE THREAD

**Issue by linfanxxxx** [Xuezenghuigithub/xuezenghui.com#23]
看到您相关的文章来的，请教一下graphQL api的一些问题，问题如下：
1. 我想拉去gitlab的groups、users、projects等数据，私有化部署等gitlab版本是13.
x，在官方文档上没有找到groups这一类型，想请教下，如果想用graphQL api 查询用户所能看到的所有groups要怎么实现
2. 是不是graphQL api 还没有完全对齐restful api？ 觉得缺少了好多

望指教！

**Comment by Xuezenghuigithub** [comment]
不好意思，这段时间有些忙没有关注 GitHub，不知道你的问题有没有解决？

1. 是有这个接口的
2. GraphQL API 的数量和支持度的确差 Restful API 很多
