### ISSUE TITLE
请问Poetry是如何将内容居中的？

### ISSUE THREAD

**Issue by driftingdream** [Xuezenghuigithub/xuezenghui.com#4]
<img width="610" alt="image" src="https://user-images.githubusercontent.com/16973422/87846632-d131ad00-c903-11ea-9db6-c71c4200d061.png">
按照你的 config.toml 我只能实现成这样，无法实现垂直居中。请问你是如何做到的？
<img width="679" alt="image" src="https://user-images.githubusercontent.com/16973422/87846640-e1498c80-c903-11ea-9feb-ac4953e51d7a.png">

**Comment by Xuezenghuigithub** [comment]
@driftingdream  垂直居中需要在样式文件中设置 padding 或者 margin，可参考我的实现 [xuezenghui.com/assets/scss/custom/_custom.scss](https://github.com/Xuezenghuigithub/xuezenghui.com/blob/2025c6c88d83b940ff63e9cbf4002462b2ebedf3/assets/scss/custom/_custom.scss#L3)

**Comment by driftingdream** [comment]
> @driftingdream 垂直居中需要在样式文件中设置 padding 或者 margin，可参考我的实现 [xuezenghui.com/assets/scss/custom/_custom.scss](https://github.com/Xuezenghuigithub/xuezenghui.com/blob/2025c6c88d83b940ff63e9cbf4002462b2ebedf3/assets/scss/custom/_custom.scss#L3)

谢谢！学习到了
